spring.application.name=ExpertsPro_CRUD_Task
spring.datasource.url=jdbc:postgresql://localhost:5432/ExpertsPro_CRUD
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect